services:
  mongodb-logs:
    image: mongo:latest
    container_name: mongodb-logs
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
    - "27018:27017"
  rabbitmq:
        image: rabbitmq:3-management 
        container_name: rabbitmq-videos
        ports:
        - "5672:5672"       
        - "15672:15672"    
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest